#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

filetype="$( file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi

if [[ "$filetype" =~ ^video ]]; then
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(~/.local/scripts/miscellaneous/vidthumb "$file")" < /dev/null > /dev/tty
    exit 1
fi

pistol "$file"

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
*.tar*) tar tf "$file" ;;
*.zip) unzip -l "$file" ;;
*.rar) unrar l "$file" ;;
*.7z) 7z l "$file" ;;
*.pdf)
	thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
	gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
	preview "$thumbnail" "$@"
	;;
*.svg)
	thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
	gm convert "$file" "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.gif)
	thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
	gm convert "$file[0]" "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*) cat "$file" ;;
esac
return 127
