#!/usr/bin/env bash

# Original script by @speltriao on GitHub
# https://github.com/speltriao/Pacman-Update-for-GNOME-Shell

PASSWD="123"

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

# Calculate updates for each service
AUR=$(paru -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)
# Calculate total number of updates
COUNT=$((OFFICIAL+AUR))

# Case/switch for each service updates
case $1 in
    aur) echo " $AUR";;
    official) echo " $OFFICIAL";;
esac

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # If there are updates, the script will output the following:  
    # If there are no updates, the script will output nothing.

    if [[ "$COUNT" = "0" ]]
    then
        echo ""
    else
        # This Update symbol is RTL. So &#x202d; is left-to-right override.
        echo " $COUNT"
    fi
# If the parameter is "update", update all services
elif [ "$1" = "update" ]; then
    # kitty --title update-sys sh -c 'paru -Syu'
    kitty --title update-sys sh -c 'sudo pacman -Sy --noconfirm && sudo powerpill -Su --noconfirm && paru -Su --noconfirm --needed'
# If parameters is "show", return the total number of updates
elif [ "$1" = "show" ]; then
    # If there are updates, the script will output the following:   Updates
    # If there are no updates, the script will output nothing.

    if [[ "$COUNT" = "0" ]]
    then
        echo ""
    else
        # This Update symbol is RTL. So &#x202d; is left-to-right override.
        echo " $COUNT"
    fi
fi
exit 0
